"""Init

Revision ID: d23f9cb1d48b
Revises: 078eeab268bd
Create Date: 2023-06-30 11:37:17.097174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23f9cb1d48b'
down_revision = '078eeab268bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
