"""Init

Revision ID: 71fb148b617e
Revises: e9c125e6827e
Create Date: 2023-05-13 16:26:31.742773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fb148b617e'
down_revision = 'e9c125e6827e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
